/**
 * Generated by build/assets.py. Do not edit by hand.
 *
 * Maps each image stem to the widths that actually exist on disk, plus the
 * intrinsic size of the largest one. Nothing is upscaled during processing,
 * so a 540px source has no 1200px variant: asking for one is a 404 that only
 * shows up in the browser console.
 */
export interface ImageMeta {
  widths: number[];
  width: number;
  height: number;
}

export const IMAGES: Record<string, ImageMeta> = {
  'audi': { widths: [640, 1024], width: 1024, height: 768 },
  'challenger': { widths: [640, 1024], width: 1024, height: 768 },
  'job-audi-1': { widths: [603], width: 603, height: 481 },
  'job-audi-2': { widths: [603], width: 603, height: 481 },
  'job-audi-after': { widths: [640, 1080], width: 1080, height: 810 },
  'job-merc-1': { widths: [636], width: 636, height: 508 },
  'job-merc-2': { widths: [636], width: 636, height: 508 },
  'job-merc-after': { widths: [640, 1080], width: 1080, height: 748 },
  'job-splatter-1': { widths: [640, 677], width: 677, height: 504 },
  'job-splatter-2': { widths: [640, 677], width: 677, height: 504 },
  'job-splatter-3': { widths: [640, 677], width: 677, height: 504 },
  'job-splatter-after': { widths: [640, 1010], width: 1010, height: 748 },
  'job-tarago-after': { widths: [640, 1080], width: 1080, height: 829 },
  'job-tarago-before': { widths: [640, 1080], width: 1080, height: 810 },
  'job-ute-1': { widths: [540], width: 540, height: 395 },
  'job-ute-2': { widths: [540], width: 540, height: 395 },
  'job-ute-3': { widths: [540], width: 540, height: 395 },
  'job-ute-4': { widths: [540], width: 540, height: 395 },
  'job-ute-after-1': { widths: [564], width: 564, height: 421 },
  'job-ute-after-2': { widths: [564], width: 564, height: 421 },
  'landcruiser': { widths: [640, 1024], width: 1024, height: 768 },
  'ram': { widths: [640, 1024], width: 1024, height: 768 },
  'suv-black': { widths: [640, 1024], width: 1024, height: 768 },
  'svc-cement': { widths: [640, 700], width: 700, height: 480 },
  'svc-fallout': { widths: [640, 800], width: 800, height: 390 },
  'svc-graffiti': { widths: [640, 800], width: 800, height: 390 },
  'svc-overspray': { widths: [640, 700], width: 700, height: 480 },
  'texture-wide': { widths: [640, 1200, 1920, 2070], width: 2070, height: 1380 },
  'van-wash': { widths: [640, 1024], width: 1024, height: 768 },
  'wheel-a': { widths: [640, 1024], width: 1024, height: 768 },
  'wheel-b': { widths: [640, 1024], width: 1024, height: 768 },
  'workshop': { widths: [614], width: 614, height: 410 },
};
